-- COMPLETE DATABASE SETUP
-- Run this entire script in Supabase SQL Editor to initialize the database.

-- 0. CLEANUP (resets the database)
-- We drop tables in reverse dependency order to avoid errors.
drop table if exists public.request_history;
drop table if exists public.products;
drop table if exists public.product_requests;
drop table if exists public.category_assignments;
drop table if exists public.vendors;
drop table if exists public.workflow_steps;
drop table if exists public.profiles;

-- 1. Profiles Table (Extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  role text default 'vendor' not null check (role in ('category_manager', 'purchasing_manager', 'assistant_purchasing_director', 'planning_director', 'commercial_executive_director', 'general_manager', 'exec_director', 'general_director', 'erp_team', 'super_admin', 'vendor')),
  department text,
  job_title text,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Vendors Table
create table public.vendors (
  id uuid default gen_random_uuid() primary key,
  company_name text not null,
  cr_number text,
  vat_number text,
  contact_person_id uuid references public.profiles(id),
  status text default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Workflow Steps Table
create table public.workflow_steps (
  step_number int primary key,
  step_name text not null,
  role_required text not null,
  sla_hours int default 24,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Category Assignments Table
create table public.category_assignments (
  id bigint generated by default as identity primary key,
  division_name text not null,
  category_manager_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(division_name, category_manager_id)
);

-- 5. Product Requests Table (Header)
create table public.product_requests (
  id uuid default gen_random_uuid() primary key,
  request_number text unique, -- Generated ID
  request_type text not null, -- 'new_vendor' | 'new_products'
  vendor_id uuid references public.vendors(id),
  created_by uuid references public.profiles(id),
  current_step int default 1 references public.workflow_steps(step_number),
  status text default 'draft',
  priority text default 'normal',
  category text, -- Matches division_name
  notes text,
  submitted_at timestamp with time zone,
  last_action_at timestamp with time zone default now(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Products Table (Line Items)
create table public.products (
  id uuid default gen_random_uuid() primary key,
  request_id uuid references public.product_requests(id) on delete cascade not null,
  
  -- Basic Info
  brand text,
  product_name text not null,
  product_name_ar text,
  item_description text,
  barcode text,
  manufacturer text,
  country_of_origin text,
  storage_condition text,
  pack_size text,
  
  -- Hierarchy
  division text,
  department text,
  category text,
  sub_category text,
  class_name text,
  
  -- Prices & Specs
  uom text,
  price_cost numeric,
  price_retail numeric,
  erp_item_code text,
  
  -- Additional Fields
  purchasing_status text,
  moh_discount_percentage numeric,
  invoice_extra_discount numeric,
  site_no text,
  vendor_no text,
  case_count int,
  lot_indicator boolean,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Request History / Logs Table
create table public.request_history (
  id uuid default gen_random_uuid() primary key,
  request_id uuid references public.product_requests(id) on delete cascade not null,
  user_id uuid references public.profiles(id),
  action text not null, -- 'submit', 'approve', 'reject', 'return'
  comment text,
  step_number int,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.vendors enable row level security;
alter table public.workflow_steps enable row level security;
alter table public.category_assignments enable row level security;
alter table public.product_requests enable row level security;
alter table public.products enable row level security;
alter table public.request_history enable row level security;

-- 9. Basic Policies (Development Mode - Allow All Authenticated)
-- WARNING: Refine these before production based on Roles!
create policy "Allow all for authenticated" on profiles for all using (auth.role() = 'authenticated');
create policy "Allow all for authenticated" on vendors for all using (auth.role() = 'authenticated');
create policy "Allow all for authenticated" on workflow_steps for all using (auth.role() = 'authenticated');
create policy "Allow all for authenticated" on category_assignments for all using (auth.role() = 'authenticated');
create policy "Allow all for authenticated" on product_requests for all using (auth.role() = 'authenticated');
create policy "Allow all for authenticated" on products for all using (auth.role() = 'authenticated');
create policy "Allow all for authenticated" on request_history for all using (auth.role() = 'authenticated');

-- 10. Handle New User Function
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id, 
    coalesce(new.email, 'unknown'), -- Handle null emails safely
    coalesce(new.raw_user_meta_data->>'full_name', ''), 
    coalesce(new.raw_user_meta_data->>'role', 'vendor')
  )
  on conflict (id) do nothing; -- Prevents crash if profile already exists
  return new;
end;
$$ language plpgsql security definer;

-- Trigger
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 11. Seed Workflow Steps (Required for foreign keys)
insert into public.workflow_steps (step_number, step_name, role_required, sla_hours) values
  (1, 'Category Manager Approval', 'category_manager', 24),
  (2, 'Purchasing Manager Approval', 'purchasing_manager', 24),
  (3, 'Assistant Purchasing Director Approval', 'assistant_purchasing_director', 48),
  (4, 'Planning Director Approval', 'planning_director', 24),
  (5, 'Commercial and BD Exec Director', 'commercial_executive_director', 48),
  (6, 'General Director Approval', 'general_manager', 48),
  (7, 'ERP Code Issuance', 'erp_team', 24);
