-- 1. Profiles Table (Extends Supabase Auth)
-- This table automatically updates when a user signs up if you use detailed triggers, 
-- or you manage it manually for staff.
create table public.profiles (
  id uuid references auth.users not null primary key, -- specific to Supabase Auth
  email text unique not null,
  full_name text,
  role text check (role in ('category_manager', 'purchasing_manager', 'assistant_purchasing_director', 'planning_director', 'commercial_business_development_executive_director', 'exec_director', 'general_director', 'planning_erp_creation', 'super_admin', 'vendor')),
  department text, -- For employees
  job_title text,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Category Authorization Table
-- Maps a specific division/node in the hierarchy to a Category Manager
create table public.category_assignments (
  id bigint generated by default as identity primary key,
  division_name text not null, -- e.g., "COSMETIC", "BABY CARE". Must match hierarchy.json names exactly.
  category_manager_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(division_name, category_manager_id)
);

-- 3. Row Level Security (RLS) Policies (Examples)

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.category_assignments enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Admins can insert category assignments"
  on category_assignments for insert
  with check ( auth.uid() in (select id from profiles where role = 'super_admin') );

-- 4. Function to handle new user creation (Optional automation)
-- This automatically creates a profile entry when a user is created in Supabase Auth
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'role');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
